import type { Metadata } from "next";

import "@/styles/main.css";
import { ViewTransitions } from "next-view-transitions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body>
          <main className="mx-auto max-w-[692px] overflow-x-hidden px-6 py-12 text-gray-1200 antialiased sm:py-32 md:overflow-x-visible md:py-16">
            <article className="article">{children}</article>
          </main>
        </body>
      </html>
    </ViewTransitions>
  );
}
